# Generated by Django 4.0.6 on 2022-09-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=5, null=True),
        ),
    ]
